version: '3'

volumes:
  pg_project:

services:
  web:
    build: .
    container_name: show_room_app
    restart: always
    command: sh ./start.sh
    volumes:
      - .:/usr/src/show_room_app
    ports:
      - "8000:8000"
    depends_on:
      - pq_db

  pq_db:
    container_name: postgres-app
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST=${SQL_HOST}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_DB=${SQL_NAME}
    volumes:
      - pg_project:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
